import { anton, oswald, parisienne, roboto_condensed } from "@/fonts";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ThemeManager from "./ThemeManager";
import ThemeToggler from "@/components/ui/ThemeToggler";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${oswald.variable} ${anton.variable} ${parisienne.variable} ${roboto_condensed.variable} bg-amber-50 dark:bg-zinc-900 text-zinc-700 dark:text-amber-50 relative font-oswald antialiased cursor-none`}
        >
          <ThemeManager>{children}</ThemeManager>
        </body>
      </StoreProvider>
    </html>
  );
}
